### ISSUE TITLE
Make split-window-sensibly work as before

### ISSUE THREAD

**Issue by akirak** [mpwang/perfect-margin#1]
When `perfect-margin-mode` is turned on, windows seem to be always split horizontally (i.e. into top and bottom windows). 

This probably relates to the behaviour of `split-window-sensibly`, so I had better suggest you override the function, like `olivetti-mode` does: https://github.com/rnkn/olivetti/blob/master/olivetti.el#L382

**Comment by mpwang** [comment]
Thanks for your suggestion!  I just update to add customization on what window to ignore setting margins. 

This minor mode is not like `olivetti-mode` it keeps everything buffer-local , which enable you to center text on one buffer while having another buffer not center text on the same frame.

This minor mode is globally applied to all windows that are not ignored.

Previously i used a hard-coded list to ignore windows to set margins. Now by default it  ignores minibuffer window and any window which name starts with "*". Many special buffer has buffer name in this pattern like `*Messages*` helm buffers. It won't touch these special buffers any more.

Hope you can play with it to suit your need.

**Comment by akirak** [comment]
Thank you for your comment.

What I meant was `perfect-margin` affected the behaviour of `split-window-sensibly`, which is used to create a new window to display a buffer. It splits a large window into a top and bottom windows, even when it should have been into left and right ones. I solved the issue by advising `window-splittable-p` function to use `perfect-margin--width-with-margins` instead of `window-width`:

```emacs-lisp
(defun akirak/perfect-margin-window-splittable-p (window &optional horizontal)
  (when (and (window-live-p window)
             (not (window-parameter window 'window-side)))
    (with-current-buffer (window-buffer window)
      (if horizontal
	  (and (memq window-size-fixed '(nil height))
	       (numberp split-width-threshold)
               ;; This part has been changed from the original version.
	       (>= (if (bound-and-true-p perfect-margin-mode)
                       (perfect-margin--width-with-margins window)
                     (window-width window))
		   (max split-width-threshold
			(* 2 (max window-min-width 2)))))
	(and (memq window-size-fixed '(nil width))
	     (numberp split-height-threshold)
	     (>= (window-height window)
		 (max split-height-threshold
		      (* 2 (max window-min-height
				(if mode-line-format 2 1))))))))))

(advice-add #'window-splittable-p :override
            #'akirak/perfect-margin-window-splittable-p)
```

Your new feature to support an ignore list is useful any way, and I also added support for ignoring windows by major modes (#3). Hope it helps!
