### ISSUE TITLE
setting margins breaks term mode

### ISSUE THREAD

**Issue by russell** [mpwang/perfect-margin#10]
I don't know the internals of term well enough to explain why, but removing the fringe wrecks `term-mode`. These screenshots are from running fzf in term mode.  And i have added `term-mode` to `perfect-margin-ignore-modes` but it doesn't disable the perfect margins for those modes.

https://github.com/mpwang/perfect-margin/blob/master/perfect-margin.el#L258

before
![Screen Shot 2021-06-11 at 18 07 17](https://user-images.githubusercontent.com/2660/121716375-3c6a0c00-cae0-11eb-88d4-e661a7db1927.png)

after
![Screen Shot 2021-06-11 at 18 07 58](https://user-images.githubusercontent.com/2660/121716391-425fed00-cae0-11eb-8680-004246e927ff.png)

**Comment by mpwang** [comment]
Sorry for the late response. I suspect that term mode is not related to the issue. Will look at fzf later. Thx!
2021年6月12日 +0800 AM12:13 Russell Sim ***@***.***>，写道：
