### ISSUE TITLE
Margins are not applied to the minibuffer when using eshell

### ISSUE THREAD

**Issue by arael** [mpwang/perfect-margin#15]
The minibuffer started in the eshell does not get the margins. Is there any way to set it?

![image](https://github.com/mpwang/perfect-margin/assets/587072/aabe80f1-02af-41a1-9139-b3263f468b71)

**Comment by mpwang** [comment]
this package does not modify the special buffer by default (minibuffer is a speical buffer), you can set

`(setq perfect-margin-ignore-filters nil)`

to center the minibuffer
