### ISSUE TITLE
This package seems to break posframes

### ISSUE THREAD

**Issue by ann4n** [mpwang/perfect-margin#16]
[A lot](https://github.com/search?q=posframe&type=repositories) of packages use [posframe](https://github.com/tumashu/posframe) including ivy posframe, helm posframe, company posframe, etc. They all break with this package. The frame slowly gets wider and then the whole thing jumps off-screen. Maybe this package should ignore posframes?

**Comment by mpwang** [comment]
the posframe buffer name might be the problem, for example 
[
(defcustom ivy-posframe-buffer " \*ivy-posframe-buffer\*"](https://github.com/tumashu/ivy-posframe/blob/533a8e368fcabfd534761a5c685ce713376fa594/ivy-posframe.el#L235C43-L235C43)  

it starts with a whitespace while perfect-margin ignores buffers whose name starts with \*, might be fixed possibly by updating the ignore-regex, will update soon
