### ISSUE TITLE
Add support for perfect-margin to work in the main buffer when a sidebar like org-side-tree is opened.

### ISSUE THREAD

**Issue by IceAsteroid** [mpwang/perfect-margin#19]
First of all, thank you @mpwang for the energy and effort spent in this package. It has become a must need for a wide monitor that I use daily!

------------------

Perfect-margin seems to not keep working when a certain sidebar window is opened. Closing that sidebar would bring back effect of perfect-margin in the main buffer.

For those of you that may wonder, why not add a general solution to support various sidebar windows but to instead open an issue for a particular specific sidebar, see issue: https://github.com/mpwang/perfect-margin/issues/17

**Comment by mpwang** [comment]
Org-side-tree is a nice package and I'd like to use it too. Thanks for the suggestion.

After much effort I have rewritten the core logic to support using side window on the left and/or right side on the same time! 

And also added the org-side-tree support, please try the latest and enjoy it.
