### ISSUE TITLE
`split-window-right` gives error: *Window #<window 35 on somefile.txt> too small for splitting*

### ISSUE THREAD

**Issue by KaratasFurkan** [mpwang/perfect-margin#20]
Hi, first of all, thanks for this great package. It's one of the main features of my workflow. However, after your recent updates, I started to get these errors. When I try to split window right (`C-x 3`), it complains about window size and doesn't split. I use Emacs fullscreen and with `perfect-margin-visible-width = 120`, so window is not actually small.

What do you think?

**Comment by mpwang** [comment]
It might be caused by my deletion of split-window advice, it set the margin of window to 0 before spliting widnow.
I must forget why I added the advice at the first place.

I added it back, please try the latest version, see if the problem persist.

**Comment by KaratasFurkan** [comment]
Seems alright now, thanks a lot!
