### ISSUE TITLE
Activate per buffer

### ISSUE THREAD

**Issue by xl666** [mpwang/perfect-margin#21]
First of all thanks for the package, it is an improvement over olivetti mode, I'm just missing a per-buffer activation (like olivetti has). Is it possible to achieve?

Thanks in advance.

**Comment by mpwang** [comment]
this mode is a global minor mode, so per-buffer setting is not the design goal. i'm afraid that it is not possible to achieve this without significant modifications.

**Comment by xl666** [comment]
Thanks, at the end I implementig my own simpler version ussing set-window-margins
