### ISSUE TITLE
Window too small for splitting

### ISSUE THREAD

**Issue by averrin** [mpwang/perfect-margin#4]
I'm trying to use perfect-margin with doom and when I exec `evil-window-vsplit` it fails with `Window too small for splitting`, but I have only one window.

**Comment by mpwang** [comment]
Sorry for the late reply, I'm afraid i need more information to diagnose. 
Could not recreate the issue on my laptop.

**Comment by averrin** [comment]
I tried on other laptop with same doom settings. Same error.
My doom.d her: https://github.com/averrin/configs/tree/master/doom.d

**Comment by averrin** [comment]
After today doom upgrade this issue disappeared.
