### ISSUE TITLE
Add option to keep small margins

### ISSUE THREAD

**Issue by n8m4** [mpwang/perfect-margin#6]
Could you add option to keep some margins when windows are split? Same for buffers that start with *. Thanks.

**Comment by mpwang** [comment]
Sorry for this terrible late reply.  Could you elaborate ? 
Acutually buffers that start with `*` are ignored by this mode, maybe the margin you mentioned is set by some other modes?

**Comment by melodrom** [comment]
Id actually love that too! I think my issue is the same one as his: as soon as i load perfect-margins-mode it removes all margins/fringes, which is a problem with stuff like https://github.com/sheijk/hideshowvis which seems to rely on a fringe/small margin and doesnt show up without one.
