### ISSUE TITLE
Not working for info?

### ISSUE THREAD

**Issue by ksqsf** [mpwang/perfect-margin#7]
`M-x info` seems not affected by perfect-margin-mode.

**Comment by mpwang** [comment]
Sorry for this terrible late reply.

minibuffer window and any window whos name starts with "*"  is ignored, you can change this behavior by setting `perfect-margin-ignore-regexps`.  Its default value is `'("^minibuf" "^[*]")`

you can remove `^[*]`, so this mode can do the job for you

**Comment by ksqsf** [comment]
Thanks! Removing `^[*]` works.
